//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaploGrepSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaploGrepSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chr	start	end	haplotypeReference	haplotypeAlternate	name	name2	transcriptStrand	positionType	frame	mrnaCoord	codonCoord	spliceDist	referenceCodon	referenceAA	variantCodon	variantAA	changesAA	functionalClass	codingCoordStr	proteinCoordStr	inCodingRegion	spliceInfo	uorfChange
        ///CRS	577	577	*	*	TRNF	tRNA-Phe	+	non_coding_exon		1		1										splice-acceptor_1	
        ///CRS	578	578	*	*	TRNF	tRNA-Phe	+	non_coding_exon		2		2										splice-acceptor_2	
        ///CRS	579	579	*	*	TRNF	tRNA-Phe	+	non_coding_exon		3		3										splice-acc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string crs_rn_bigtable {
            get {
                return ResourceManager.GetString("crs_rn_bigtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChrPos	Nuc_change	AA_change	Gene	Disease	Type
        ///CRS:582	T-C	noncoding	MT-TF	Mitochondrial Myopathy	RNAMutation
        ///CRS:583	G-A	noncoding	MT-TF	MELAS / MM &amp; EXIT	RNAMutation
        ///CRS:586	G-A	noncoding	MT-TF	Extrapyramidal Disorder with Akinesia-Rigidity, Psychosis and SNHL	RNAMutation
        ///CRS:606	A-G	noncoding	MT-TF	Myoglobinuria	RNAMutation
        ///CRS:608	A-G	noncoding	MT-TF	Tubulointerstitial nephritis	RNAMutation
        ///CRS:611	G-A	noncoding	MT-TF	MERRF	RNAMutation
        ///CRS:618	T-C	noncoding	MT-TF	MM	RNAMutation
        ///CRS:622	G-A	noncoding	MT-T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mitomap_dz_mutations_110126_filtered_110916 {
            get {
                return ResourceManager.GetString("mitomap_dz_mutations_110126_filtered_110916", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChrPos	Nuc_change	AA_change	Gene	Disease	Type
        ///CRS:583	G-A	noncoding	MT-TF	MELAS / MM &amp; EXIT	RNAMutation
        ///CRS:1494	C-T	noncoding	MT-RNR1	DEAF	RNAMutation
        ///CRS:1555	A-G	noncoding	MT-RNR1	DEAF	RNAMutation
        ///CRS:1606	G-A	noncoding	MT-TV	AMDF	RNAMutation
        ///CRS:3243	A-G	noncoding	MT-TL1	MELAS / LS	RNAMutation
        ///CRS:3243	A-G	noncoding	MT-TL1	DMDF / MIDD / SNHL / FSGS	RNAMutation
        ///CRS:3243	A-G	noncoding	MT-TL1	CPEO / MM	RNAMutation
        ///CRS:3243	A-T	noncoding	MT-TL1	MM / MELAS / SNHL / CPEO	RNAMutation
        ///CRS:3256	C-T	noncoding	MT- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mitomap_dz_mutations_110126_filtered_110916_confirmed_120126 {
            get {
                return ResourceManager.GetString("mitomap_dz_mutations_110126_filtered_110916_confirmed_120126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chr:start	mtDB_maf
        ///CRS:3	0.000536193
        ///CRS:9	0.000536193
        ///CRS:10	0.002144772
        ///CRS:11	0.000536193
        ///CRS:41	0.001072386
        ///CRS:42	0.000536193
        ///CRS:55	0.003217158
        ///CRS:57	0.001608579
        ///CRS:59	0.001072386
        ///CRS:61	0.001072386
        ///CRS:62	0.001608579
        ///CRS:63	0.003217158
        ///CRS:64	0.014477212
        ///CRS:66	0.001610306
        ///CRS:68	0.003217158
        ///CRS:69	0.000536193
        ///CRS:70	0.000536193
        ///CRS:72	0.038069705
        ///CRS:73	0.166219839
        ///CRS:75	0.001072386
        ///CRS:84	0.000536193
        ///CRS:89	0.005898123
        ///CRS:92	0.003217158
        ///CRS:93	0.021983914
        ///CRS:94	0.009651475
        ///CRS:95	0.003753351
        ///C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mtDB_sorted_crs_rn {
            get {
                return ResourceManager.GetString("mtDB_sorted_crs_rn", resourceCulture);
            }
        }
    }
}
